### ISSUE TITLE
csp:s now no longer have if exists drop

### ISSUE THREAD

**Issue by LarsCJensen** [Lundalogik/addon-lip-package-builder#29]
1.2.1 had that. Has other stuff gotten reverted?

**Comment by LarsCJensen** [comment]
I assigned it to you Fredrik since you made the release and might know what has happened?

**Comment by justFredster** [comment]
Hm. Don't know what happened. I must have f***d up somehow. The code is still there in the the tags for v2.0.0. But not in the LIP zip attached to the release. I will fix that by making a new LIP zip file.

Great catch! Thanks @LarsCJensen !

**Comment by justFredster** [comment]
I have replaced the LIP zip file now.

@LarsCJensen will this be automatically updated in Lime Store even though it is not a new release?

**Comment by LarsCJensen** [comment]
It is just a link in the database, so if the link is the same it should work. But I don’t know if the link is changed when you update a file.

**Comment by justFredster** [comment]
The link should be the same, so should work then. Tested to download in Lime Store, they are now back!
