### ISSUE TITLE
Should Lundalogik/lip be public?

### ISSUE THREAD

**Issue by claasahl** [Lundalogik/addon-lip-package-builder#32]
The readme of this repository says that this repo was merged with [Lundalogik/lip](https://github.com/Lundalogik/lip). This repository is public, should `Lundalogik/lip` also be public?

**Comment by justFredster** [comment]
No, it should not be anymore. It was made private a few years back. But thank you for reminding us that this repo should have its issues transferred to the lip repo and that we should archive this repo. :)

(So I will archive it now).
